# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f34d0de79922b53375fa97fbfdec9ca91905f319111eb5579a3b919353977dbb7f4c0824f20ff4325d31814d3018da578acaff4596984a01ef9b5479fb2ee5c

test:
  secret_key_base: 5f427980406896c6f38a4a9065d9d4b4ec649db7aa8a0c1faa9dcaed19d24080f17e3f35c329a27d32cc1649544c60c65225853528a5abb06e05cfdf9d6a3a49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
